//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NW.Payment.Wrappers.EparaWs {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="v2Soap", Namespace="http://tempuri.org/")]
    public partial class v2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private FirmCredentials firmCredentialsValueField;
        
        private System.Threading.SendOrPostCallback CreateWithdrawal_onlyBlokesizHavaleOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateWithdrawal_onlyHizliPaparaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGroupListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBankListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getWithdrawalStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDepositStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDepositLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDepositLink_PosOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckCompletedWithdrawalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckWithdrawalResult_byTransactionIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback CompleteWithdrawalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisableWithdrawalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckCompletedDepositsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CompleteDepositsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckDepositResult_byTransactionIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public v2() {
            this.Url = global::NW.Payment.Wrappers.Properties.Settings.Default.NW_Payment_Wrappers_EparaWs_v2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public FirmCredentials FirmCredentialsValue {
            get {
                return this.firmCredentialsValueField;
            }
            set {
                this.firmCredentialsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateWithdrawal_onlyBlokesizHavaleCompletedEventHandler CreateWithdrawal_onlyBlokesizHavaleCompleted;
        
        /// <remarks/>
        public event CreateWithdrawal_onlyHizliPaparaCompletedEventHandler CreateWithdrawal_onlyHizliPaparaCompleted;
        
        /// <remarks/>
        public event getGroupListCompletedEventHandler getGroupListCompleted;
        
        /// <remarks/>
        public event getBankListCompletedEventHandler getBankListCompleted;
        
        /// <remarks/>
        public event getWithdrawalStatusCompletedEventHandler getWithdrawalStatusCompleted;
        
        /// <remarks/>
        public event getDepositStatusCompletedEventHandler getDepositStatusCompleted;
        
        /// <remarks/>
        public event CreateDepositLinkCompletedEventHandler CreateDepositLinkCompleted;
        
        /// <remarks/>
        public event CreateDepositLink_PosCompletedEventHandler CreateDepositLink_PosCompleted;
        
        /// <remarks/>
        public event CheckCompletedWithdrawalsCompletedEventHandler CheckCompletedWithdrawalsCompleted;
        
        /// <remarks/>
        public event CheckWithdrawalResult_byTransactionIDCompletedEventHandler CheckWithdrawalResult_byTransactionIDCompleted;
        
        /// <remarks/>
        public event CompleteWithdrawalsCompletedEventHandler CompleteWithdrawalsCompleted;
        
        /// <remarks/>
        public event DisableWithdrawalsCompletedEventHandler DisableWithdrawalsCompleted;
        
        /// <remarks/>
        public event CheckCompletedDepositsCompletedEventHandler CheckCompletedDepositsCompleted;
        
        /// <remarks/>
        public event CompleteDepositsCompletedEventHandler CompleteDepositsCompleted;
        
        /// <remarks/>
        public event CheckDepositResult_byTransactionIDCompletedEventHandler CheckDepositResult_byTransactionIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateWithdrawal_onlyBlokesizHavale", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_RETURN CreateWithdrawal_onlyBlokesizHavale(ent_WithdrawalAdding ent) {
            object[] results = this.Invoke("CreateWithdrawal_onlyBlokesizHavale", new object[] {
                        ent});
            return ((ent_RETURN)(results[0]));
        }
        
        /// <remarks/>
        public void CreateWithdrawal_onlyBlokesizHavaleAsync(ent_WithdrawalAdding ent) {
            this.CreateWithdrawal_onlyBlokesizHavaleAsync(ent, null);
        }
        
        /// <remarks/>
        public void CreateWithdrawal_onlyBlokesizHavaleAsync(ent_WithdrawalAdding ent, object userState) {
            if ((this.CreateWithdrawal_onlyBlokesizHavaleOperationCompleted == null)) {
                this.CreateWithdrawal_onlyBlokesizHavaleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateWithdrawal_onlyBlokesizHavaleOperationCompleted);
            }
            this.InvokeAsync("CreateWithdrawal_onlyBlokesizHavale", new object[] {
                        ent}, this.CreateWithdrawal_onlyBlokesizHavaleOperationCompleted, userState);
        }
        
        private void OnCreateWithdrawal_onlyBlokesizHavaleOperationCompleted(object arg) {
            if ((this.CreateWithdrawal_onlyBlokesizHavaleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateWithdrawal_onlyBlokesizHavaleCompleted(this, new CreateWithdrawal_onlyBlokesizHavaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateWithdrawal_onlyHizliPapara", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_RETURN CreateWithdrawal_onlyHizliPapara(ent_WithdrawalAdding_HizliPapara ent) {
            object[] results = this.Invoke("CreateWithdrawal_onlyHizliPapara", new object[] {
                        ent});
            return ((ent_RETURN)(results[0]));
        }
        
        /// <remarks/>
        public void CreateWithdrawal_onlyHizliPaparaAsync(ent_WithdrawalAdding_HizliPapara ent) {
            this.CreateWithdrawal_onlyHizliPaparaAsync(ent, null);
        }
        
        /// <remarks/>
        public void CreateWithdrawal_onlyHizliPaparaAsync(ent_WithdrawalAdding_HizliPapara ent, object userState) {
            if ((this.CreateWithdrawal_onlyHizliPaparaOperationCompleted == null)) {
                this.CreateWithdrawal_onlyHizliPaparaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateWithdrawal_onlyHizliPaparaOperationCompleted);
            }
            this.InvokeAsync("CreateWithdrawal_onlyHizliPapara", new object[] {
                        ent}, this.CreateWithdrawal_onlyHizliPaparaOperationCompleted, userState);
        }
        
        private void OnCreateWithdrawal_onlyHizliPaparaOperationCompleted(object arg) {
            if ((this.CreateWithdrawal_onlyHizliPaparaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateWithdrawal_onlyHizliPaparaCompleted(this, new CreateWithdrawal_onlyHizliPaparaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getGroupList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_LIST[] getGroupList() {
            object[] results = this.Invoke("getGroupList", new object[0]);
            return ((ent_LIST[])(results[0]));
        }
        
        /// <remarks/>
        public void getGroupListAsync() {
            this.getGroupListAsync(null);
        }
        
        /// <remarks/>
        public void getGroupListAsync(object userState) {
            if ((this.getGroupListOperationCompleted == null)) {
                this.getGroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGroupListOperationCompleted);
            }
            this.InvokeAsync("getGroupList", new object[0], this.getGroupListOperationCompleted, userState);
        }
        
        private void OngetGroupListOperationCompleted(object arg) {
            if ((this.getGroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGroupListCompleted(this, new getGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getBankList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_LIST[] getBankList(int group_id) {
            object[] results = this.Invoke("getBankList", new object[] {
                        group_id});
            return ((ent_LIST[])(results[0]));
        }
        
        /// <remarks/>
        public void getBankListAsync(int group_id) {
            this.getBankListAsync(group_id, null);
        }
        
        /// <remarks/>
        public void getBankListAsync(int group_id, object userState) {
            if ((this.getBankListOperationCompleted == null)) {
                this.getBankListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBankListOperationCompleted);
            }
            this.InvokeAsync("getBankList", new object[] {
                        group_id}, this.getBankListOperationCompleted, userState);
        }
        
        private void OngetBankListOperationCompleted(object arg) {
            if ((this.getBankListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBankListCompleted(this, new getBankListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getWithdrawalStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getWithdrawalStatus() {
            object[] results = this.Invoke("getWithdrawalStatus", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getWithdrawalStatusAsync() {
            this.getWithdrawalStatusAsync(null);
        }
        
        /// <remarks/>
        public void getWithdrawalStatusAsync(object userState) {
            if ((this.getWithdrawalStatusOperationCompleted == null)) {
                this.getWithdrawalStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWithdrawalStatusOperationCompleted);
            }
            this.InvokeAsync("getWithdrawalStatus", new object[0], this.getWithdrawalStatusOperationCompleted, userState);
        }
        
        private void OngetWithdrawalStatusOperationCompleted(object arg) {
            if ((this.getWithdrawalStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWithdrawalStatusCompleted(this, new getWithdrawalStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDepositStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getDepositStatus() {
            object[] results = this.Invoke("getDepositStatus", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getDepositStatusAsync() {
            this.getDepositStatusAsync(null);
        }
        
        /// <remarks/>
        public void getDepositStatusAsync(object userState) {
            if ((this.getDepositStatusOperationCompleted == null)) {
                this.getDepositStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDepositStatusOperationCompleted);
            }
            this.InvokeAsync("getDepositStatus", new object[0], this.getDepositStatusOperationCompleted, userState);
        }
        
        private void OngetDepositStatusOperationCompleted(object arg) {
            if ((this.getDepositStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDepositStatusCompleted(this, new getDepositStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateDepositLink", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_RETURN CreateDepositLink(int group_id, string user_login_username, string user_full_name, string transactionID, string accountType) {
            object[] results = this.Invoke("CreateDepositLink", new object[] {
                        group_id,
                        user_login_username,
                        user_full_name,
                        transactionID,
                        accountType});
            return ((ent_RETURN)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDepositLinkAsync(int group_id, string user_login_username, string user_full_name, string transactionID, string accountType) {
            this.CreateDepositLinkAsync(group_id, user_login_username, user_full_name, transactionID, accountType, null);
        }
        
        /// <remarks/>
        public void CreateDepositLinkAsync(int group_id, string user_login_username, string user_full_name, string transactionID, string accountType, object userState) {
            if ((this.CreateDepositLinkOperationCompleted == null)) {
                this.CreateDepositLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDepositLinkOperationCompleted);
            }
            this.InvokeAsync("CreateDepositLink", new object[] {
                        group_id,
                        user_login_username,
                        user_full_name,
                        transactionID,
                        accountType}, this.CreateDepositLinkOperationCompleted, userState);
        }
        
        private void OnCreateDepositLinkOperationCompleted(object arg) {
            if ((this.CreateDepositLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDepositLinkCompleted(this, new CreateDepositLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateDepositLink_Pos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_RETURN CreateDepositLink_Pos(string user_login_username, string transactionID, int amount, int ExpireMonth, int ExpireYear, string CardNumber, string CardOwner, string CVV) {
            object[] results = this.Invoke("CreateDepositLink_Pos", new object[] {
                        user_login_username,
                        transactionID,
                        amount,
                        ExpireMonth,
                        ExpireYear,
                        CardNumber,
                        CardOwner,
                        CVV});
            return ((ent_RETURN)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDepositLink_PosAsync(string user_login_username, string transactionID, int amount, int ExpireMonth, int ExpireYear, string CardNumber, string CardOwner, string CVV) {
            this.CreateDepositLink_PosAsync(user_login_username, transactionID, amount, ExpireMonth, ExpireYear, CardNumber, CardOwner, CVV, null);
        }
        
        /// <remarks/>
        public void CreateDepositLink_PosAsync(string user_login_username, string transactionID, int amount, int ExpireMonth, int ExpireYear, string CardNumber, string CardOwner, string CVV, object userState) {
            if ((this.CreateDepositLink_PosOperationCompleted == null)) {
                this.CreateDepositLink_PosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDepositLink_PosOperationCompleted);
            }
            this.InvokeAsync("CreateDepositLink_Pos", new object[] {
                        user_login_username,
                        transactionID,
                        amount,
                        ExpireMonth,
                        ExpireYear,
                        CardNumber,
                        CardOwner,
                        CVV}, this.CreateDepositLink_PosOperationCompleted, userState);
        }
        
        private void OnCreateDepositLink_PosOperationCompleted(object arg) {
            if ((this.CreateDepositLink_PosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDepositLink_PosCompleted(this, new CreateDepositLink_PosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckCompletedWithdrawals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_Withdrawal[] CheckCompletedWithdrawals() {
            object[] results = this.Invoke("CheckCompletedWithdrawals", new object[0]);
            return ((ent_Withdrawal[])(results[0]));
        }
        
        /// <remarks/>
        public void CheckCompletedWithdrawalsAsync() {
            this.CheckCompletedWithdrawalsAsync(null);
        }
        
        /// <remarks/>
        public void CheckCompletedWithdrawalsAsync(object userState) {
            if ((this.CheckCompletedWithdrawalsOperationCompleted == null)) {
                this.CheckCompletedWithdrawalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckCompletedWithdrawalsOperationCompleted);
            }
            this.InvokeAsync("CheckCompletedWithdrawals", new object[0], this.CheckCompletedWithdrawalsOperationCompleted, userState);
        }
        
        private void OnCheckCompletedWithdrawalsOperationCompleted(object arg) {
            if ((this.CheckCompletedWithdrawalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckCompletedWithdrawalsCompleted(this, new CheckCompletedWithdrawalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckWithdrawalResult_byTransactionID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_Withdrawal CheckWithdrawalResult_byTransactionID(string transactionID) {
            object[] results = this.Invoke("CheckWithdrawalResult_byTransactionID", new object[] {
                        transactionID});
            return ((ent_Withdrawal)(results[0]));
        }
        
        /// <remarks/>
        public void CheckWithdrawalResult_byTransactionIDAsync(string transactionID) {
            this.CheckWithdrawalResult_byTransactionIDAsync(transactionID, null);
        }
        
        /// <remarks/>
        public void CheckWithdrawalResult_byTransactionIDAsync(string transactionID, object userState) {
            if ((this.CheckWithdrawalResult_byTransactionIDOperationCompleted == null)) {
                this.CheckWithdrawalResult_byTransactionIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckWithdrawalResult_byTransactionIDOperationCompleted);
            }
            this.InvokeAsync("CheckWithdrawalResult_byTransactionID", new object[] {
                        transactionID}, this.CheckWithdrawalResult_byTransactionIDOperationCompleted, userState);
        }
        
        private void OnCheckWithdrawalResult_byTransactionIDOperationCompleted(object arg) {
            if ((this.CheckWithdrawalResult_byTransactionIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckWithdrawalResult_byTransactionIDCompleted(this, new CheckWithdrawalResult_byTransactionIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CompleteWithdrawals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_RETURN[] CompleteWithdrawals(string[] transactionIDs) {
            object[] results = this.Invoke("CompleteWithdrawals", new object[] {
                        transactionIDs});
            return ((ent_RETURN[])(results[0]));
        }
        
        /// <remarks/>
        public void CompleteWithdrawalsAsync(string[] transactionIDs) {
            this.CompleteWithdrawalsAsync(transactionIDs, null);
        }
        
        /// <remarks/>
        public void CompleteWithdrawalsAsync(string[] transactionIDs, object userState) {
            if ((this.CompleteWithdrawalsOperationCompleted == null)) {
                this.CompleteWithdrawalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompleteWithdrawalsOperationCompleted);
            }
            this.InvokeAsync("CompleteWithdrawals", new object[] {
                        transactionIDs}, this.CompleteWithdrawalsOperationCompleted, userState);
        }
        
        private void OnCompleteWithdrawalsOperationCompleted(object arg) {
            if ((this.CompleteWithdrawalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompleteWithdrawalsCompleted(this, new CompleteWithdrawalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DisableWithdrawals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_RETURN[] DisableWithdrawals(string[] transactionIDs) {
            object[] results = this.Invoke("DisableWithdrawals", new object[] {
                        transactionIDs});
            return ((ent_RETURN[])(results[0]));
        }
        
        /// <remarks/>
        public void DisableWithdrawalsAsync(string[] transactionIDs) {
            this.DisableWithdrawalsAsync(transactionIDs, null);
        }
        
        /// <remarks/>
        public void DisableWithdrawalsAsync(string[] transactionIDs, object userState) {
            if ((this.DisableWithdrawalsOperationCompleted == null)) {
                this.DisableWithdrawalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisableWithdrawalsOperationCompleted);
            }
            this.InvokeAsync("DisableWithdrawals", new object[] {
                        transactionIDs}, this.DisableWithdrawalsOperationCompleted, userState);
        }
        
        private void OnDisableWithdrawalsOperationCompleted(object arg) {
            if ((this.DisableWithdrawalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisableWithdrawalsCompleted(this, new DisableWithdrawalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckCompletedDeposits", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_Deposit[] CheckCompletedDeposits() {
            object[] results = this.Invoke("CheckCompletedDeposits", new object[0]);
            return ((ent_Deposit[])(results[0]));
        }
        
        /// <remarks/>
        public void CheckCompletedDepositsAsync() {
            this.CheckCompletedDepositsAsync(null);
        }
        
        /// <remarks/>
        public void CheckCompletedDepositsAsync(object userState) {
            if ((this.CheckCompletedDepositsOperationCompleted == null)) {
                this.CheckCompletedDepositsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckCompletedDepositsOperationCompleted);
            }
            this.InvokeAsync("CheckCompletedDeposits", new object[0], this.CheckCompletedDepositsOperationCompleted, userState);
        }
        
        private void OnCheckCompletedDepositsOperationCompleted(object arg) {
            if ((this.CheckCompletedDepositsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckCompletedDepositsCompleted(this, new CheckCompletedDepositsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CompleteDeposits", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_RETURN[] CompleteDeposits(string[] transactionIDs) {
            object[] results = this.Invoke("CompleteDeposits", new object[] {
                        transactionIDs});
            return ((ent_RETURN[])(results[0]));
        }
        
        /// <remarks/>
        public void CompleteDepositsAsync(string[] transactionIDs) {
            this.CompleteDepositsAsync(transactionIDs, null);
        }
        
        /// <remarks/>
        public void CompleteDepositsAsync(string[] transactionIDs, object userState) {
            if ((this.CompleteDepositsOperationCompleted == null)) {
                this.CompleteDepositsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompleteDepositsOperationCompleted);
            }
            this.InvokeAsync("CompleteDeposits", new object[] {
                        transactionIDs}, this.CompleteDepositsOperationCompleted, userState);
        }
        
        private void OnCompleteDepositsOperationCompleted(object arg) {
            if ((this.CompleteDepositsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompleteDepositsCompleted(this, new CompleteDepositsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("FirmCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckDepositResult_byTransactionID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ent_Deposit CheckDepositResult_byTransactionID(string transactionID) {
            object[] results = this.Invoke("CheckDepositResult_byTransactionID", new object[] {
                        transactionID});
            return ((ent_Deposit)(results[0]));
        }
        
        /// <remarks/>
        public void CheckDepositResult_byTransactionIDAsync(string transactionID) {
            this.CheckDepositResult_byTransactionIDAsync(transactionID, null);
        }
        
        /// <remarks/>
        public void CheckDepositResult_byTransactionIDAsync(string transactionID, object userState) {
            if ((this.CheckDepositResult_byTransactionIDOperationCompleted == null)) {
                this.CheckDepositResult_byTransactionIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckDepositResult_byTransactionIDOperationCompleted);
            }
            this.InvokeAsync("CheckDepositResult_byTransactionID", new object[] {
                        transactionID}, this.CheckDepositResult_byTransactionIDOperationCompleted, userState);
        }
        
        private void OnCheckDepositResult_byTransactionIDOperationCompleted(object arg) {
            if ((this.CheckDepositResult_byTransactionIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckDepositResult_byTransactionIDCompleted(this, new CheckDepositResult_byTransactionIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class FirmCredentials : System.Web.Services.Protocols.SoapHeader {
        
        private System.Guid firmKeyField;
        
        private string secretKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public System.Guid FirmKey {
            get {
                return this.firmKeyField;
            }
            set {
                this.firmKeyField = value;
            }
        }
        
        /// <remarks/>
        public string SecretKey {
            get {
                return this.secretKeyField;
            }
            set {
                this.secretKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ent_Deposit {
        
        private string transactionIDField;
        
        private string user_login_usernameField;
        
        private string user_full_nameField;
        
        private System.DateTime created_dateField;
        
        private System.Nullable<System.DateTime> completed_dateField;
        
        private double amountField;
        
        private string statusField;
        
        private string status_detailField;
        
        private int group_idField;
        
        private int bank_idField;
        
        private string bank_nameField;
        
        private string group_nameField;
        
        private System.Guid actionGuidField;
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string user_login_username {
            get {
                return this.user_login_usernameField;
            }
            set {
                this.user_login_usernameField = value;
            }
        }
        
        /// <remarks/>
        public string user_full_name {
            get {
                return this.user_full_nameField;
            }
            set {
                this.user_full_nameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime created_date {
            get {
                return this.created_dateField;
            }
            set {
                this.created_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> completed_date {
            get {
                return this.completed_dateField;
            }
            set {
                this.completed_dateField = value;
            }
        }
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string status_detail {
            get {
                return this.status_detailField;
            }
            set {
                this.status_detailField = value;
            }
        }
        
        /// <remarks/>
        public int group_id {
            get {
                return this.group_idField;
            }
            set {
                this.group_idField = value;
            }
        }
        
        /// <remarks/>
        public int bank_id {
            get {
                return this.bank_idField;
            }
            set {
                this.bank_idField = value;
            }
        }
        
        /// <remarks/>
        public string bank_name {
            get {
                return this.bank_nameField;
            }
            set {
                this.bank_nameField = value;
            }
        }
        
        /// <remarks/>
        public string group_name {
            get {
                return this.group_nameField;
            }
            set {
                this.group_nameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid actionGuid {
            get {
                return this.actionGuidField;
            }
            set {
                this.actionGuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ent_Withdrawal {
        
        private string transactionIDField;
        
        private string user_login_usernameField;
        
        private string user_full_nameField;
        
        private string tCNoField;
        
        private string iBANField;
        
        private System.DateTime created_dateField;
        
        private System.Nullable<System.DateTime> completed_dateField;
        
        private double amountField;
        
        private string statusField;
        
        private string status_detailField;
        
        private int group_idField;
        
        private int bank_idField;
        
        private string bank_nameField;
        
        private string group_nameField;
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string user_login_username {
            get {
                return this.user_login_usernameField;
            }
            set {
                this.user_login_usernameField = value;
            }
        }
        
        /// <remarks/>
        public string user_full_name {
            get {
                return this.user_full_nameField;
            }
            set {
                this.user_full_nameField = value;
            }
        }
        
        /// <remarks/>
        public string TCNo {
            get {
                return this.tCNoField;
            }
            set {
                this.tCNoField = value;
            }
        }
        
        /// <remarks/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime created_date {
            get {
                return this.created_dateField;
            }
            set {
                this.created_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> completed_date {
            get {
                return this.completed_dateField;
            }
            set {
                this.completed_dateField = value;
            }
        }
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string status_detail {
            get {
                return this.status_detailField;
            }
            set {
                this.status_detailField = value;
            }
        }
        
        /// <remarks/>
        public int group_id {
            get {
                return this.group_idField;
            }
            set {
                this.group_idField = value;
            }
        }
        
        /// <remarks/>
        public int bank_id {
            get {
                return this.bank_idField;
            }
            set {
                this.bank_idField = value;
            }
        }
        
        /// <remarks/>
        public string bank_name {
            get {
                return this.bank_nameField;
            }
            set {
                this.bank_nameField = value;
            }
        }
        
        /// <remarks/>
        public string group_name {
            get {
                return this.group_nameField;
            }
            set {
                this.group_nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ent_LIST {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ent_WithdrawalAdding_HizliPapara {
        
        private string user_login_usernameField;
        
        private string user_full_nameField;
        
        private string paparaNoField;
        
        private string tCNoField;
        
        private double amountField;
        
        private string transactionIDField;
        
        /// <remarks/>
        public string user_login_username {
            get {
                return this.user_login_usernameField;
            }
            set {
                this.user_login_usernameField = value;
            }
        }
        
        /// <remarks/>
        public string user_full_name {
            get {
                return this.user_full_nameField;
            }
            set {
                this.user_full_nameField = value;
            }
        }
        
        /// <remarks/>
        public string PaparaNo {
            get {
                return this.paparaNoField;
            }
            set {
                this.paparaNoField = value;
            }
        }
        
        /// <remarks/>
        public string TCNo {
            get {
                return this.tCNoField;
            }
            set {
                this.tCNoField = value;
            }
        }
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ent_RETURN {
        
        private bool successField;
        
        private string descriptionField;
        
        private string transactionIDField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ent_WithdrawalAdding {
        
        private string user_login_usernameField;
        
        private string user_full_nameField;
        
        private string iBANField;
        
        private string tCNoField;
        
        private double amountField;
        
        private int bank_idField;
        
        private string transactionIDField;
        
        private string birthdayField;
        
        private string hesap_noField;
        
        private string sube_koduField;
        
        private string tc_yakiniField;
        
        private string kimlik_tarihField;
        
        /// <remarks/>
        public string user_login_username {
            get {
                return this.user_login_usernameField;
            }
            set {
                this.user_login_usernameField = value;
            }
        }
        
        /// <remarks/>
        public string user_full_name {
            get {
                return this.user_full_nameField;
            }
            set {
                this.user_full_nameField = value;
            }
        }
        
        /// <remarks/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
        
        /// <remarks/>
        public string TCNo {
            get {
                return this.tCNoField;
            }
            set {
                this.tCNoField = value;
            }
        }
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public int bank_id {
            get {
                return this.bank_idField;
            }
            set {
                this.bank_idField = value;
            }
        }
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        public string hesap_no {
            get {
                return this.hesap_noField;
            }
            set {
                this.hesap_noField = value;
            }
        }
        
        /// <remarks/>
        public string sube_kodu {
            get {
                return this.sube_koduField;
            }
            set {
                this.sube_koduField = value;
            }
        }
        
        /// <remarks/>
        public string tc_yakini {
            get {
                return this.tc_yakiniField;
            }
            set {
                this.tc_yakiniField = value;
            }
        }
        
        /// <remarks/>
        public string kimlik_tarih {
            get {
                return this.kimlik_tarihField;
            }
            set {
                this.kimlik_tarihField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateWithdrawal_onlyBlokesizHavaleCompletedEventHandler(object sender, CreateWithdrawal_onlyBlokesizHavaleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateWithdrawal_onlyBlokesizHavaleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateWithdrawal_onlyBlokesizHavaleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_RETURN Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_RETURN)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateWithdrawal_onlyHizliPaparaCompletedEventHandler(object sender, CreateWithdrawal_onlyHizliPaparaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateWithdrawal_onlyHizliPaparaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateWithdrawal_onlyHizliPaparaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_RETURN Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_RETURN)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getGroupListCompletedEventHandler(object sender, getGroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_LIST[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_LIST[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getBankListCompletedEventHandler(object sender, getBankListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBankListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBankListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_LIST[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_LIST[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getWithdrawalStatusCompletedEventHandler(object sender, getWithdrawalStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWithdrawalStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getWithdrawalStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getDepositStatusCompletedEventHandler(object sender, getDepositStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDepositStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDepositStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateDepositLinkCompletedEventHandler(object sender, CreateDepositLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDepositLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDepositLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_RETURN Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_RETURN)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateDepositLink_PosCompletedEventHandler(object sender, CreateDepositLink_PosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDepositLink_PosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDepositLink_PosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_RETURN Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_RETURN)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckCompletedWithdrawalsCompletedEventHandler(object sender, CheckCompletedWithdrawalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckCompletedWithdrawalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckCompletedWithdrawalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_Withdrawal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_Withdrawal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckWithdrawalResult_byTransactionIDCompletedEventHandler(object sender, CheckWithdrawalResult_byTransactionIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckWithdrawalResult_byTransactionIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckWithdrawalResult_byTransactionIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_Withdrawal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_Withdrawal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CompleteWithdrawalsCompletedEventHandler(object sender, CompleteWithdrawalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompleteWithdrawalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CompleteWithdrawalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_RETURN[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_RETURN[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DisableWithdrawalsCompletedEventHandler(object sender, DisableWithdrawalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisableWithdrawalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisableWithdrawalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_RETURN[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_RETURN[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckCompletedDepositsCompletedEventHandler(object sender, CheckCompletedDepositsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckCompletedDepositsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckCompletedDepositsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_Deposit[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_Deposit[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CompleteDepositsCompletedEventHandler(object sender, CompleteDepositsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompleteDepositsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CompleteDepositsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_RETURN[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_RETURN[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckDepositResult_byTransactionIDCompletedEventHandler(object sender, CheckDepositResult_byTransactionIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckDepositResult_byTransactionIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckDepositResult_byTransactionIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ent_Deposit Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ent_Deposit)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591